### ISSUE TITLE
Websockets are breaking when including wrap-restful-format

### ISSUE THREAD

**Issue by sveri** [sveri/closp#15]
This is brought in by n.u.middleware/app-handler and used in foo.bar.handler by providing extra params: :formats [:json-kw :edn :transit-json].

It will fail with this error message:

Thu Dec 17 16:14:29 CET 2015 [worker-3] ERROR - GET /stockfighter/qoutes/ws
com.fasterxml.jackson.core.JsonGenerationException: Cannot JSON encode object of class: class org.httpkit.server.AsyncChannel: /0:0:0:0:0:0:0:1:3000<->/0:0:0:0:0:0:0:1:60401
    at cheshire.generate$generate$fn__4631.invoke(generate.clj:122)
    at cheshire.generate$generate.invoke(generate.clj:122)
    at cheshire.core$generate_string.invoke(core.clj:31)
    at cheshire.core$generate_string.invoke(core.clj:19)
    at ring.middleware.format_response$wrap_format_response$fn__19188.invoke(format_response.clj:184)
    at noir.validation$wrap_noir_validation$fn__18692.invoke(validation.clj:155)
    at noir.cookies$noir_cookies$fn__18753.invoke(cookies.clj:72)
    at ring.middleware.cookies$wrap_cookies$fn__16100.invoke(cookies.clj:161)
    at noir.session$noir_flash$fn__16316.invoke(session.clj:158)
    at ring.middleware.flash$wrap_flash$fn__16241.invoke(flash.clj:35)
    at noir.session$noir_session$fn__16302.invoke(session.clj:109)
    at ring.middleware.session_timeout$wrap_idle_session_timeout$fn__16258.invoke(session_timeout.clj:25)
    at ring.middleware.session$wrap_session$fn__16221.invoke(session.clj:102)
    at ring.middleware.file$wrap_file$fn__18499.invoke(file.clj:44)
    at org.httpkit.server.HttpHandler.run(RingHandler.java:91)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

See if we can remove that safely.

**Comment by sveri** [comment]
The correct approach is to use different routes with that with different middleware set.
